language: node_js
node_js:
  - node

cache: npm

before_script:
  - npm i -g codecov

script:
  - npm run lint
  - npm run test

notifications:
  email: false
  webhooks:
    urls:
      - https://mechilles.garkaklis.com/
    on_success: change

after_success:
  - codecov
